[package]
name = "video_on_demand_transcoding_service"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
tokio = { workspace = true }
async-nats = { workspace = true }
futures = { workspace = true }
