services:
  video_service:
    container_name: video_service
    build:
      context: .
      dockerfile: ./services/video/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - localstack
      - nats
      - db
    volumes:
      - ./services/video:/usr/src/app/services/video

  transcoding_service:
    container_name: transcoding_service
    build:
      context: .
      dockerfile: ./services/transcoding/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - localstack
      - nats
    volumes:
      - ./services/transcoding:/usr/src/app/services/transcoding
    environment:
      - NATS_URL=nats://nats:4222

  notification_service:
    container_name: notification_service
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - nats
    volumes:
      - ./services/notification:/usr/src/app/services/notification

  nats:
    image: nats:2.10
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--http_port 8222 -js"

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: testing
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.7
    ports:
      - 4566:4566
    volumes:
      - ./scripts/localstack/setup.sh:/etc/localstack/init/ready.d/script.sh

volumes:
  pgdata:
